FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

COPY . .

RUN npx prisma generate

ENV NODE_ENV production
ENV SOCKET_PORT 3001

EXPOSE 3001

CMD ["npm", "run", "socket:start"]
