import { FeeType, TaxApplicationMode, TaxType } from '@prisma/client'

export const SERVICE_FEE_CATEGORY_SEEDS = [
  { code: 'TRANSACTION', name: 'Transaction Service Fees', sortOrder: 1 },
  { code: 'ESCROW', name: 'Escrow Service Fees', sortOrder: 2 },
  { code: 'SHIPPING', name: 'Shipping Commission', sortOrder: 3 },
  { code: 'VERIFICATION', name: 'Verification Fees', sortOrder: 4 },
  { code: 'INSPECTION', name: 'Inspection Commission', sortOrder: 5 },
  { code: 'INSURANCE', name: 'Insurance Commission', sortOrder: 6 },
  { code: 'AI_PREMIUM', name: 'AI Premium Services', sortOrder: 7 },
  { code: 'RFQ_CREDIT', name: 'RFQ Credits', sortOrder: 8 },
  { code: 'TRADE_DOCUMENT', name: 'Trade Documentation', sortOrder: 9 },
  { code: 'COMPLIANCE', name: 'Customs & Compliance', sortOrder: 10 },
  { code: 'SAMPLE_ORDER', name: 'Sample Order Fees', sortOrder: 11 },
  { code: 'DISPUTE', name: 'Dispute Resolution', sortOrder: 12 },
  { code: 'ENTERPRISE_API', name: 'Enterprise Integration', sortOrder: 13 },
  { code: 'REFUND_POLICY', name: 'Refund Policy', sortOrder: 14 },
] as const

export const SERVICE_FEE_SETTING_SEEDS = [
  {
    code: 'TRANSACTION_SERVICE_FEE',
    name: 'Transaction Service Fee',
    categoryCode: 'TRANSACTION',
    feeType: FeeType.PERCENTAGE,
    feeValue: 2,
    currency: 'USD',
    appliesTo: 'TRADE_ORDER_COMPLETION',
    description: 'Platform profit deducted from completed trade orders before supplier payout.',
  },
  {
    code: 'ESCROW_SERVICE_FEE',
    name: 'Escrow Service Fee',
    categoryCode: 'ESCROW',
    feeType: FeeType.PERCENTAGE,
    feeValue: 2,
    currency: 'USD',
    appliesTo: 'TRADE_ORDER_ESCROW',
    description: 'Escrow holding fee charged when buyer funds escrow.',
  },
  {
    code: 'SHIPPING_COMMISSION',
    name: 'Shipping Commission',
    categoryCode: 'SHIPPING',
    feeType: FeeType.PERCENTAGE,
    feeValue: 5,
    currency: 'USD',
    appliesTo: 'LOGISTICS_BOOKING',
    description: 'Commission applied to shipping booked through the platform.',
  },
  {
    code: 'VERIFICATION_BUSINESS_LICENSE',
    name: 'Business License Verification Fee',
    categoryCode: 'VERIFICATION',
    feeType: FeeType.FIXED,
    feeValue: 75,
    currency: 'USD',
    appliesTo: 'BUSINESS_LICENSE_VERIFICATION',
    description: 'Verification fee for business license review.',
  },
  {
    code: 'VERIFICATION_FACTORY',
    name: 'Factory Verification Fee',
    categoryCode: 'VERIFICATION',
    feeType: FeeType.FIXED,
    feeValue: 150,
    currency: 'USD',
    appliesTo: 'FACTORY_VERIFICATION',
    description: 'Verification fee for factory validation requests.',
  },
  {
    code: 'VERIFICATION_EXPORT_LICENSE',
    name: 'Export License Verification Fee',
    categoryCode: 'VERIFICATION',
    feeType: FeeType.FIXED,
    feeValue: 95,
    currency: 'USD',
    appliesTo: 'EXPORT_LICENSE_VERIFICATION',
    description: 'Verification fee for export license checks.',
  },
  {
    code: 'VERIFICATION_TAX',
    name: 'Tax Verification Fee',
    categoryCode: 'VERIFICATION',
    feeType: FeeType.FIXED,
    feeValue: 65,
    currency: 'USD',
    appliesTo: 'TAX_VERIFICATION',
    description: 'Verification fee for tax record checks.',
  },
  {
    code: 'INSPECTION_SERVICE_FEE',
    name: 'Inspection Commission',
    categoryCode: 'INSPECTION',
    feeType: FeeType.PERCENTAGE,
    feeValue: 8,
    currency: 'USD',
    appliesTo: 'FACTORY_INSPECTION',
    description: 'Platform commission on factory audit and inspection services.',
  },
  {
    code: 'INSURANCE_CARGO',
    name: 'Cargo Insurance Commission',
    categoryCode: 'INSURANCE',
    feeType: FeeType.PERCENTAGE,
    feeValue: 6,
    currency: 'USD',
    appliesTo: 'CARGO_INSURANCE',
    description: 'Commission for cargo insurance policies arranged through the platform.',
  },
  {
    code: 'INSURANCE_MARINE',
    name: 'Marine Insurance Commission',
    categoryCode: 'INSURANCE',
    feeType: FeeType.PERCENTAGE,
    feeValue: 6,
    currency: 'USD',
    appliesTo: 'MARINE_INSURANCE',
    description: 'Commission for marine insurance policies arranged through the platform.',
  },
  {
    code: 'INSURANCE_CONTAINER',
    name: 'Container Insurance Commission',
    categoryCode: 'INSURANCE',
    feeType: FeeType.PERCENTAGE,
    feeValue: 6,
    currency: 'USD',
    appliesTo: 'CONTAINER_INSURANCE',
    description: 'Commission for container insurance policies arranged through the platform.',
  },
  {
    code: 'AI_PREMIUM_PLAN',
    name: 'AI Premium Plan Fee',
    categoryCode: 'AI_PREMIUM',
    feeType: FeeType.FIXED,
    feeValue: 49,
    currency: 'USD',
    appliesTo: 'AI_SUBSCRIPTION',
    description: 'Base fee used when creating AI premium subscription plans.',
  },
  {
    code: 'RFQ_CREDIT_PACKAGE',
    name: 'RFQ Credit Package Fee',
    categoryCode: 'RFQ_CREDIT',
    feeType: FeeType.FIXED,
    feeValue: 30,
    currency: 'USD',
    appliesTo: 'RFQ_CREDIT_PURCHASE',
    description: 'Default price anchor for RFQ credit packages.',
  },
  {
    code: 'TRADE_DOCUMENT_COMMERCIAL_INVOICE',
    name: 'Commercial Invoice Fee',
    categoryCode: 'TRADE_DOCUMENT',
    feeType: FeeType.FIXED,
    feeValue: 10,
    currency: 'USD',
    appliesTo: 'COMMERCIAL_INVOICE',
    description: 'Platform fee for generating a commercial invoice.',
  },
  {
    code: 'TRADE_DOCUMENT_PACKING_LIST',
    name: 'Packing List Fee',
    categoryCode: 'TRADE_DOCUMENT',
    feeType: FeeType.FIXED,
    feeValue: 8,
    currency: 'USD',
    appliesTo: 'PACKING_LIST',
    description: 'Platform fee for generating a packing list.',
  },
  {
    code: 'TRADE_DOCUMENT_CERTIFICATE_OF_ORIGIN',
    name: 'Certificate of Origin Fee',
    categoryCode: 'TRADE_DOCUMENT',
    feeType: FeeType.FIXED,
    feeValue: 18,
    currency: 'USD',
    appliesTo: 'CERTIFICATE_OF_ORIGIN',
    description: 'Platform fee for generating a certificate of origin.',
  },
  {
    code: 'TRADE_DOCUMENT_EXPORT_DOCUMENT',
    name: 'Export Document Fee',
    categoryCode: 'TRADE_DOCUMENT',
    feeType: FeeType.FIXED,
    feeValue: 15,
    currency: 'USD',
    appliesTo: 'EXPORT_DOCUMENT',
    description: 'Platform fee for generating export documentation.',
  },
  {
    code: 'COMPLIANCE_HS_CODE',
    name: 'HS Code Assistance Fee',
    categoryCode: 'COMPLIANCE',
    feeType: FeeType.FIXED,
    feeValue: 12,
    currency: 'USD',
    appliesTo: 'HS_CODE_ASSISTANCE',
    description: 'Fee for HS code assistance.',
  },
  {
    code: 'COMPLIANCE_CUSTOMS_DOCUMENTATION',
    name: 'Customs Documentation Fee',
    categoryCode: 'COMPLIANCE',
    feeType: FeeType.FIXED,
    feeValue: 20,
    currency: 'USD',
    appliesTo: 'CUSTOMS_DOCUMENTATION',
    description: 'Fee for customs documentation support.',
  },
  {
    code: 'COMPLIANCE_DUTY_CALCULATION',
    name: 'Duty Calculation Fee',
    categoryCode: 'COMPLIANCE',
    feeType: FeeType.FIXED,
    feeValue: 16,
    currency: 'USD',
    appliesTo: 'DUTY_CALCULATION',
    description: 'Fee for duty and landed cost calculation support.',
  },
  {
    code: 'COMPLIANCE_EXPORT_COMPLIANCE',
    name: 'Export Compliance Fee',
    categoryCode: 'COMPLIANCE',
    feeType: FeeType.FIXED,
    feeValue: 25,
    currency: 'USD',
    appliesTo: 'EXPORT_COMPLIANCE',
    description: 'Fee for export compliance support.',
  },
  {
    code: 'SAMPLE_ORDER_SERVICE_FEE',
    name: 'Sample Order Service Fee',
    categoryCode: 'SAMPLE_ORDER',
    feeType: FeeType.PERCENTAGE,
    feeValue: 3,
    currency: 'USD',
    appliesTo: 'SAMPLE_ORDER',
    description: 'Service fee applied when buyer places a sample order.',
  },
  {
    code: 'DISPUTE_RESOLUTION_FEE',
    name: 'Dispute Resolution Fee',
    categoryCode: 'DISPUTE',
    feeType: FeeType.FREE,
    feeValue: 0,
    currency: 'USD',
    appliesTo: 'DISPUTE_CASE',
    description: 'Dispute mediation fee managed dynamically by admin.',
  },
  {
    code: 'ENTERPRISE_API_SUBSCRIPTION',
    name: 'Enterprise API Subscription',
    categoryCode: 'ENTERPRISE_API',
    feeType: FeeType.FIXED,
    feeValue: 500,
    currency: 'USD',
    appliesTo: 'ENTERPRISE_API_SUBSCRIPTION',
    description: 'Enterprise integration plan fee. Disabled by default until needed.',
    isActive: false,
  },
  {
    code: 'NON_REFUNDABLE_PLATFORM_FEE',
    name: 'Non-Refundable Platform Fee',
    categoryCode: 'REFUND_POLICY',
    feeType: FeeType.PERCENTAGE,
    feeValue: 100,
    currency: 'USD',
    appliesTo: 'REFUND_POLICY',
    description: 'Percentage of platform fee kept during refunds unless admin overrides.',
  },
] as const

export const TAX_VAT_SETTING_SEEDS = [
  {
    code: 'VAT_BD_STANDARD',
    country: 'Bangladesh',
    stateRegion: null,
    taxName: 'VAT',
    taxRate: 15,
    taxType: TaxType.VAT,
    applicationMode: TaxApplicationMode.EXCLUSIVE,
    appliesToBuyer: true,
    appliesToSupplier: false,
    appliesToServiceFee: true,
    appliesToSubscription: true,
  },
  {
    code: 'VAT_GB_DIGITAL',
    country: 'United Kingdom',
    stateRegion: null,
    taxName: 'VAT',
    taxRate: 20,
    taxType: TaxType.VAT,
    applicationMode: TaxApplicationMode.EXCLUSIVE,
    appliesToBuyer: true,
    appliesToSupplier: false,
    appliesToServiceFee: true,
    appliesToSubscription: true,
  },
] as const
